In [22]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[[1,2,3],[4,5,6]],[[3,2,1],[6,5,4]],[[7,8,9],[9,8,7]]])
print(a.shape,a.ndim)
print(b.shape,b.ndim)
print(c.shape,c.ndim)


(4,) 1
(2, 3) 2
(3, 2, 3) 3


In [23]:
np.arange(10,51,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [24]:
rm=np.random.choice(np.arange(1, 21), size=(3, 3))
rm

array([[12, 14, 20],
       [ 3,  6,  8],
       [19,  5,  6]])

In [25]:
print(rm[1,:])

[3 6 8]


In [26]:
print(rm[:,1])

[14  6  5]


In [27]:
subarray = rm[0:2, 1:4]
subarray

array([[14, 20],
       [ 6,  8]])

In [28]:
rm[rm%2==0]=-1
rm

array([[-1, -1, -1],
       [ 3, -1, -1],
       [19,  5, -1]])

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [31]:
m=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
m.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])