In [155]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [125]:
a.shape

(4,)

In [126]:
b=np.array([[1,2,3],[4,5,6]])
b
b.shape

(2, 3)

In [127]:
c=np.array([[[1,2,3],[4,5,6]],[[3,2,1],[6,5,4]],[[7,8,9],[9,8,7]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [6, 5, 4]],

       [[7, 8, 9],
        [9, 8, 7]]])

In [128]:
c.shape

(3, 2, 3)

In [129]:
c.ndim

3

In [130]:
a=np.array([1,2,3,4])
a**2


array([ 1,  4,  9, 16])

In [131]:
a=np.zeros((3,3,3))
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [132]:
np.random.rand(3,3)

array([[0.98106641, 0.3779059 , 0.55440204],
       [0.16559906, 0.03682209, 0.77378342],
       [0.93233413, 0.71685916, 0.5003012 ]])

In [133]:
a=np.zeros((5,6))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [134]:
a=np.ones((5,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [135]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [136]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [137]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [138]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [139]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [140]:
np.array([1,2,5,6,1,12])

array([ 1,  2,  5,  6,  1, 12])

In [141]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [142]:
np.full((2,2),2)

array([[2, 2],
       [2, 2]])

In [143]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [144]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [145]:
np.full((2,3),1)

array([[1, 1, 1],
       [1, 1, 1]])

In [146]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [147]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [148]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [149]:
np.arange(0,13,2)

array([ 0,  2,  4,  6,  8, 10, 12])

In [150]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [151]:
b=np.array(["a","b","c"])
b

array(['a', 'b', 'c'], dtype='<U1')

In [152]:
b.dtype

dtype('<U1')

In [153]:
b.shape

(3,)

In [158]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [159]:
a.ndim

1

In [161]:
a=np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [162]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [163]:
a.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [164]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)
print(a**2)

[5 7 9]
[ 4 10 18]
[1 4 9]


# Indexing and Slicing

In [165]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a[0,1])
print(a[1,2])
print(a[:,1])
print(a[1,:])


[[1 2 3]
 [4 5 6]]
2
6
[2 5]
[4 5 6]


In [167]:
a=np.array([1,2,3,4,5,6])
b=np.mean(a)
c=np.std(a)
d=np.sum(a)
e=np.max(a)
f=np.min(a)
g=np.median(a)
print(a,b,c,d,e,f,g)

[1 2 3 4 5 6] 3.5 1.707825127659933 21 6 1 3.5


In [168]:
np.random.rand(3,4)

array([[0.54026665, 0.18130575, 0.85139859, 0.80626288],
       [0.11163036, 0.32049915, 0.95316351, 0.86656756],
       [0.94076312, 0.0801329 , 0.80441508, 0.20444317]])

In [169]:
np.random.randn(3,4)

array([[-0.11600346,  0.92284989, -2.1728383 , -0.84840319],
       [ 1.42203462,  0.23192978, -1.77309755,  0.50250573],
       [ 1.12846509,  1.70960499,  1.26828142,  0.68873096]])

In [173]:
np.random.randint(2,10)

9