In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
a.shape

(4,)

In [4]:
b=np.array([[1,2,3],[4,5,6]])
b
b.shape

(2, 3)

In [5]:
c=np.array([[[1,2,3],[4,5,6]],[[3,2,1],[6,5,4]],[[7,8,9],[9,8,7]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [6, 5, 4]],

       [[7, 8, 9],
        [9, 8, 7]]])

In [6]:
c.shape

(3, 2, 3)

In [7]:
c.ndim

3

In [8]:
a=np.array([1,2,3,4])
a**2


array([ 1,  4,  9, 16])

In [11]:
a=np.zeros((3,3,3))
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
np.random.rand(3,3)

array([[0.43106764, 0.5733772 , 0.16978395],
       [0.62159412, 0.70727422, 0.84543146],
       [0.37976708, 0.49700997, 0.60443397]])